name: Run Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: action-lerna
        uses: m19c/action-lerna@1.0.0
        with:
            args: bootstrap
      - name: action-lerna
        uses: m19c/action-lerna@1.0.0
        with:
            args: run test --stream
