name: Run Tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: action-lerna
        uses: m19c/action-lerna@1.0.0
        with:
            args: bootstrap
      - run: yarn test:unit
